url    : "https://modakoda.com"
baseurl: ""

title      : Modakoda Software Development
formspree_form_path: f/mayllpep
description: "Agile Software Development and Support Services"
author     : Modakoda
logo:     #optional, defaults to site title
  path: assets\img\logo.png
  height: 50

analytics:
  google: G-G2DF9L3BTG

collections:
  portfolio:

markdown: kramdown
