header:
    title: Welcome to our Software Development Company!
    text: It's Nice To Meet You
    button: Tell Me More
    buttonlink: "#services" # "#{section}" or "URL/page link"

services:
    title: "Services"
    text: "We Help to Grow Your Business"
    section: services
    list:
      - title: "Software Development"
        desc: "Software Design and Development with full product lifecycle support."
        icon: fas fa-laptop #find more at https://fontawesome.com/icons
      - title: "Process Automation"
        desc: "Review and Automate manual processes in your business to perform faster in the market."
        icon: fas fa-chart-line      
      - title: "Support"
        desc: "Already have a product? We are ready to support it."
        icon: fas fa-headset

portfolio:
    title: "Portfolio"
    text: "We are proud of our work."
    section: portfolio
    

timeline:
    title: "About" 
    text: "This is how our journey looks like."
    section: timeline
    events:
      - title: "Company established"
        year: "2016"
        desc: "Together with co-workers we have started our journey and established Modakoda company."
        image: assets/img/timeline/1.jpg
        alt: 
        align: left
      - title: "Contract with Hansa Eule"
        year: "2016"
        desc: "Our first partner joined to start completely new product - car insurance business in Germany backed by Gefion."
        image: assets/img/timeline/2.jpg
        alt: 
        align: right
      - title: "Contract with Polins"
        year: "2017"
        desc: "Due to our successful launch of insurance product in Germany, our new partners decided to make a contract with us. We have created a new produt in PL market."
        image: assets/img/timeline/3.jpg
        alt: image alt text      
      - title: "Online Radio Search"
        year: "2019"
        desc: "Together with our great minds, we found opportunity to create a platform for searching and listening of online radio stations. This was a simple and useful product among Android users."
        image: assets/img/timeline/4.jpg
        alt: 
        align: right
    end: "Be Part <br> of Our <br> Story!"

about:
    title: "About Us"
    text: "our story"
    section: about

clients:
    section: clients
    max-height: 100px
    horizontal-scrolling: "" #"yes/no"
    list:
      - title: "hansa eule"
        url: https://service.hansa-eule.de
        logo: assets/img/clients/hansa-eule.jpg
      - title: "polins"
        url: https://polins.pl
        logo: assets/img/clients/polins.jpg
    
team:
    title: "OUR AMAZING TEAM"
    text: "We are here for your company to succeed"
    subtext: We are highly motivated Software Development professionals passionate about our work. Everything is possible with us.
    section: team
    people:
      - name: "Modestas"
        role: "Lead Developer"
        image: assets/img/team/1.jpg
        social:
          - url: https://www.linkedin.com/in/modestas-ka%C5%BEinauskas-14a87250/
            icon: fab fa-linkedin-in
          - url: https://github.com/mkazinauskas
            icon: fab fa-github
      - name: "Mindaugas"
        role: "Lead Developer"
        image: assets/img/team/2.jpg
        social:
          - url: https://facebook.com
            icon: fab fa-facebook-f
          - url: https://www.linkedin.com/in/mindaugasbaranauskas
            icon: fab fa-linkedin-in
      - name: "Živilė"
        role: "Business Analyst"
        image: assets/img/team/3.jpg
        social:
          - url: https://www.linkedin.com/in/zivile-baranauskiene-2097064/
            icon: fab fa-linkedin-in
          
contact:
    title: "Contact Us"
    text: "Let's talk <a href=\"tel:+370 600 74687\" alt=\"contact us\">+370 600 74687</a>"
    section: contact
    
footer:
    legal: "Privacy Policy"
    social: 
      - url: https://www.facebook.com/Modakoda-104451278247155
        icon: "fab fa-facebook-f"
      - url: https://github.com/modakoda
        icon: "fab fa-github"


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
